[2025-10-12T15:24:50.044+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-12T15:24:50.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_mlflow.load_processed_to_minio manual__2025-10-12T15:20:23.644157+00:00 [queued]>
[2025-10-12T15:24:50.086+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_mlflow.load_processed_to_minio manual__2025-10-12T15:20:23.644157+00:00 [queued]>
[2025-10-12T15:24:50.087+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-12T15:24:50.105+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_processed_to_minio> on 2025-10-12 15:20:23.644157+00:00
[2025-10-12T15:24:50.119+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=241) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-12T15:24:50.120+0000] {standard_task_runner.py:63} INFO - Started process 252 to run task
[2025-10-12T15:24:50.121+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_mlflow', 'load_processed_to_minio', 'manual__2025-10-12T15:20:23.644157+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/etl_mlflow.py', '--cfg-path', '/tmp/tmp0bu8bi_6']
[2025-10-12T15:24:50.122+0000] {standard_task_runner.py:91} INFO - Job 23: Subtask load_processed_to_minio
[2025-10-12T15:24:50.179+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_mlflow.load_processed_to_minio manual__2025-10-12T15:20:23.644157+00:00 [running]> on host 7920bc5e4faa
[2025-10-12T15:24:50.290+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_mlflow' AIRFLOW_CTX_TASK_ID='load_processed_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T15:20:23.644157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T15:20:23.644157+00:00'
[2025-10-12T15:24:50.292+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-12T15:24:50.384+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-10-12T15:24:50.385+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-12T15:24:50.396+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_mlflow, task_id=load_processed_to_minio, run_id=manual__2025-10-12T15:20:23.644157+00:00, execution_date=20251012T152023, start_date=20251012T152450, end_date=20251012T152450
[2025-10-12T15:24:50.456+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-12T15:24:50.478+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-12T15:24:50.481+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
